# Generated by Django 2.1.7 on 2019-03-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20190314_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='appl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdate', models.DateField()),
                ('tdate', models.DateField()),
                ('reason', models.CharField(max_length=300)),
                ('atype', models.CharField(max_length=10)),
            ],
        ),
    ]
