# Generated by Django 2.1.7 on 2019-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='grievances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=15)),
                ('grievance', models.CharField(max_length=300)),
            ],
        ),
    ]
