# Generated by Django 2.1.7 on 2019-03-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_grievances'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievances',
            name='subject',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
    ]
